name: Publish to PyPI

on:
  push:
    tags:
      - "v*"
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    name: Build wheels
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            args: "--skip-existing -r pypi --sdist"
          - os: macos-latest
            # use universal2 flag, no sdist here
            args: "--skip-existing -r pypi --universal2"
          - os: windows-latest
            # no sdist here either
            args: "--skip-existing -r pypi"
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Build and publish with maturin
        uses: PyO3/maturin-action@v1
        env:
          MATURIN_PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        with:
          command: publish
          args: ${{ matrix.args }}
          manylinux: manylinux2014   # ensure compliant Linux wheels