name: Publish to PyPI

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build wheels
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            args: "--release --skip-existing -r pypi --sdist"
          - os: macos-latest
            args: "--release --skip-existing -r pypi --sdist --target universal2-apple-darwin"
          - os: windows-latest
            args: "--release --skip-existing -r pypi --sdist"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Build and publish with maturin
        uses: PyO3/maturin-action@v1
        env:
          MATURIN_PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        with:
          command: publish
          args: ${{ matrix.args }}
