# .github/workflows/docs.yml
name: Docs
on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write
  
jobs:
  test:
    name: Test build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Create venv for maturin develop
        run: python -m venv .venv

      - name: Build with maturin & install into .venv
        uses: PyO3/maturin-action@v1
        with:
          command: develop
          args: --release
          manylinux: manylinux2014

      - name: Install Python test deps into .venv
        run: |
          . .venv/bin/activate
          pip install -e '.[dev]'

      - name: Run Python tests
        run: |
          . .venv/bin/activate
          pytest

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Run Rust tests
        run: cargo test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
